/**
 * Machine-readable warehouse schema (public/data/catalog.json), generated by
 * scripts/warehouse-build.mjs. Drives the data console's CATÁLOGO view: the
 * star-schema tables, their columns, and the cross-referencing relationships.
 */

export interface CatalogColumn {
  key: string
  tipo: string
  unidade: string
  desc: string
}

export interface CatalogTable {
  name: string
  kind: 'dimensao' | 'fato'
  grao: string
  fonte: string
  rowCount: number
  columns: CatalogColumn[]
  notas: string[]
}

export interface CatalogRelationship {
  from: string
  fromCol: string
  to: string
  toCol: string
}

export interface WarehouseCatalog {
  generatedFrom: string
  tables: CatalogTable[]
  relationships: CatalogRelationship[]
}
