/**
 * Factual public indicators (IBGE) shown as context in panels and tooltips.
 * Static files under public/data/indicators, generated by
 * scripts/fetch-indicators.mjs. Never a source for the power rankings: those
 * stay fictional until the F5/F6 pipeline + review workflow
 * (ARCHITECTURE.md section 5).
 */
export interface RegionIndicators {
  /** Censo 2022, pessoas. Null when IBGE suppressed the value. */
  population: number | null
  /** Censo 2022, km². */
  areaKm2: number | null
  /** Censo 2022, hab/km². */
  density: number | null
  /** PIB a preços correntes, em mil R$ (PIB dos Municípios). */
  gdpBrlThousands: number | null
}

export interface IndicatorsMeta {
  censusYear: number
  gdpYear: number
}

export interface UfIndicatorsFile extends IndicatorsMeta {
  /** Keyed by 'BR' or UF sigla (same join key as PowerRegion.id). */
  regions: Record<string, RegionIndicators>
}

export interface MunicipioIndicatorsFile extends IndicatorsMeta {
  /** Keyed by 7-digit IBGE municipality code. */
  municipios: Record<string, RegionIndicators>
}
